name: Python Proj

on:
  push:
    branches:
      -main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS 
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-acccess-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region: ap-south-1  

    - name: Deploy code to S3 bucket
      run: aws s3 sync . s3://aniketbucket3 --delete

    # - name: Run Script to run python file
    #   run: 

    # - name: 
    
