name: Python Proj

on:
  push:
  # pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS 
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region: ${{ secrets.AWS_REGION }}  

    - name: Deploy code to S3 bucket
      run: aws s3 sync . s3://aniketbucket3/Python-Proj --delete

    # - name: Run Script to run python file
    #   run: 

    # - name: 
